version: '3.3'

services:

  redis:
    container_name: fuel_cards-redis
    restart: always
    image: redis:alpine

  postgres:
    container_name: fuel_cards-postgres
    restart: always
    image: postgres
    env_file:
      - ./src/fuel_cards/settings/pg_credential.py
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:./data/

  django:
    container_name: fuel_cards-django
    restart: always
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - ./src/cards/migrations:/app/src/fuel_cards/migrations/
    command: "python ./src/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
      - postgres

  celery-worker:
    container_name: fuel_cards-celery_worker
    restart: always
    build:
      context: ./
    environment:
      - DEBUG=1
    command: "celery --workdir=./src -A fuel_cards worker -l info"
    depends_on:
      - redis
      - django
      - postgres

  celery-beat:
    container_name: fuel_cards-celery_beat
    restart: always
    build:
      context: ./
    command: "celery --workdir=./src -A fuel_cards beat --scheduler django_celery_beat.schedulers:DatabaseScheduler -l info"
    environment:
      - DEBUG=1
    depends_on:
      - redis
      - django
      - postgres
